import {AntdThemeProvider} from "@/app/theme";
import Header from "@/app/header";
import Footer from "@/app/footer";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import Sider from "@/app/sider";
import Content from "@/app/content";
import InnerContent from "@/app/inner-content";
import {Layout} from "antd";
import {PropsWithChildren} from "react";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

const RootLayout = async ({ children }: PropsWithChildren) => {
    const response = await fetch('http://localhost:3000/api/files');
    const files = await response.json();

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
                <AntdRegistry>
                    <AntdThemeProvider>
                        <Layout style={{ minHeight: "100dvh" }}>
                            <Header />
                            <div style={{ padding: '0 48px' }}>
                                <InnerContent>
                                    <Sider files={files} />
                                    <Content>
                                        {children}
                                    </Content>
                                </InnerContent>
                            </div>
                            <Footer />
                        </Layout>
                    </AntdThemeProvider>
                </AntdRegistry>
            </body>
        </html>
    );
};

RootLayout.displayName = "RootLayout";

export default RootLayout;
