import {AntdThemeProvider} from "@/app/theme";
import Sider from "@/app/sider";
import Content from "@/app/content";
import InnerContent from "@/app/inner-content";
import {Layout} from "antd";
import {PropsWithChildren} from "react";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import ActionPanel from "@/app/action-panel";

const geistSans = Geist({
    variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

const RootLayout = async ({ children }: PropsWithChildren) => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
                <AntdThemeProvider>
                    <Layout style={{ minHeight: "100dvh" }}>
                        <Layout>
                            <InnerContent>
                                <Sider />
                                <Content>
                                    {children}
                                </Content>
                            </InnerContent>
                            <ActionPanel />
                        </Layout>
                    </Layout>
                </AntdThemeProvider>
            </body>
        </html>
    );
};

RootLayout.displayName = "RootLayout";

export default RootLayout;
